### ISSUE TITLE
http://localhost:5000 not work 

### ISSUE THREAD

**Issue by maz1989** [adaptlearning/adapt_authoring#956] opened 2015-12-03 13:16 UTC
I done this steps :
Install Vagrant.
Install VirtualBox.
Get the code by downloading a zip directly from GitHub, or by cloning the repository using git.
Launch a terminal window (or command prompt) and cd into the adapt_authoring directory you have just downloaded. (Windows users: it is essential that you launch command prompt as an Administrator.). 
If you're unfamiliar with the terminal, have a look at our Just Enough Command Line for Installing page first.
Run the command vagrant up. (Windows users: during this process you may receive prompts from your firewall software, to which you must allow access, as installation will fail if the VM cannot access the internet to download the required dependencies.)
Depending on the performance of your hardware, allow 10 to 20 minutes for setup complete. Once it finishes, you can browse to http://localhost:5000 to access the authoring tool. 

but when I browse to http://localhost:5000 i get this error screen :

![error](https://cloud.githubusercontent.com/assets/16080780/11561533/c3393932-99d0-11e5-98f5-0fe24e736b54.PNG)

**Comment by taylortom** [comment] 2015-12-03 13:54
Do you have any ouput in the terminal window?
What operating system are you using?

**Comment by maz1989** [comment] 2015-12-03 13:59
Thank you for replay 

I am using windows 10 64bit OS 

output : 
![output](https://cloud.githubusercontent.com/assets/16080780/11562461/c67359d8-99d6-11e5-9109-e7f3d5bef09d.PNG)

**Comment by maz1989** [comment] 2015-12-07 11:22
any comment

**Comment by brian-learningpool** [comment] 2015-12-07 12:55
@maz1989, is the the output from the first time you ran `vagrant up`?

**Comment by maz1989** [comment] 2015-12-07 13:03
no ,its from next times

**Comment by brian-learningpool** [comment] 2015-12-07 15:12
There isn't enough information there to go on.  Can you run `vagrant destroy` then `vagrant up` again, and paste the output?

**Comment by maz1989** [comment] 2015-12-07 15:27
![capture](https://cloud.githubusercontent.com/assets/16080780/11630778/abd7b126-9d07-11e5-90a4-a21c47659451.PNG)

**Comment by brian-learningpool** [comment] 2015-12-08 09:20
From that output it looks like it hasn't run any of the .sh scripts required to setup the authoring tool.  I'll have to source a Windows 10 machine to debug.

**Comment by maz1989** [comment] 2015-12-08 09:35
Yon need to debug on my machine or any other windows 10 machine?
Is it general problem on all Windows 10 machines?

**Comment by maz1989** [comment] 2015-12-16 06:44
any help

**Comment by maz1989** [comment] 2015-12-21 13:16
@brian-learningpool  any help please

**Comment by brian-learningpool** [comment] 2016-01-26 14:25
@maz1989, this seems to be a consistent problem with Windows 10 machines.  We're going to try to resolve this for the next release but it's difficult as none of the core team use Windows machines.

**Comment by brian-learningpool** [comment] 2016-01-26 14:28
I'm closing this issue as it appears to be a duplicate of #1006.  That ticket will be updated with any progress.

**Closed by brian-learningpool** 2016-01-26 14:28 UTC

**Comment by Wo222ow** [comment] 2018-02-08 02:30
تب

**Comment by spiketribe610** [comment] 2019-10-10 19:56
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
ggg

g
g
gg

g
g
g
g
gg

g
g
g
gg
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g
gg
g
g
g
g
g

f

f

f
f
f
f

g
g
g
f

f
g
f

g
f
gf
h
gf
h

f
hg
g
ggg
gh

g
hgh
ghghy'h

g


h
h
h

h
hh

h
h
h
h
h
h

h

h

h
h
h
h
h

**Comment by spiketribe610** [comment] 2019-10-10 19:56
a
























































a

**Comment by spiketribe610** [comment] 2019-10-10 19:57
a
a
a
a
a
a
a
a
a
a
aa

a

a
a
a
a
a
a

a

a
a
a
a
a
a
aa
a

a
a
a
a
a
a
a
a

a

a
a

a
a
a
a
a

a
a
a
a

a
a
a

aa

d
d

dd

dd
d
d

d
d

d
d
dd
d
d
d
d
d
d
d
d
d
d
d
d


dd
d
d
d
d
d
d

d
dd

d
d
d
d
d

d
d
d
d
d
d
d
d
d
d

d

d
d
d
d
d
d

d

d
d
d
d
d
d

d

d
d
d

d
d
d
d
d

d
dd

d
d
d
a

[GitHub] Please verify your email address.InboxxGitHub <noreply@github.com>15:42 (14 minutes ago)to meAlmost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHubSent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107ReplyForward | Inbox | x | GitHub <noreply@github.com> | GitHub <noreply@github.com> | 15:42 (14 minutes ago) |   |   | to me | to me | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHubSent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHubSent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 |   |   | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub |   | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub | Verify email address | Verify email address |   | Sent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 |   |   | ReplyForward |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Inbox | x
GitHub <noreply@github.com> | GitHub <noreply@github.com> | 15:42 (14 minutes ago) |   |  
GitHub <noreply@github.com>
to me | to me
to me
Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHubSent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHubSent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 |   |   | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub |   | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub | Verify email address | Verify email address |   | Sent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 |  
Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHubSent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 |   |   | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub |   | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub | Verify email address | Verify email address |   | Sent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 |  
  |  
Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub |   | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub | Verify email address | Verify email address |  
  | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub | Verify email address | Verify email address |  
Verify email address | Verify email address
Verify email address
Sent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 |  
  | ReplyForward


[GitHub] Please verify your email address.InboxxGitHub <noreply@github.com>15:42 (14 minutes ago)to meAlmost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHubSent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107ReplyForward | Inbox | x | GitHub <noreply@github.com> | GitHub <noreply@github.com> | 15:42 (14 minutes ago) |   |   | to me | to me | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHubSent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHubSent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 |   |   | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub |   | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub | Verify email address | Verify email address |   | Sent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 |   |   | ReplyForward |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Inbox | x
GitHub <noreply@github.com> | GitHub <noreply@github.com> | 15:42 (14 minutes ago) |   |  
GitHub <noreply@github.com>
to me | to me
to me
Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHubSent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHubSent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 |   |   | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub |   | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub | Verify email address | Verify email address |   | Sent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 |  
Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHubSent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 |   |   | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub |   | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub | Verify email address | Verify email address |   | Sent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 |  
  |  
Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub |   | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub | Verify email address | Verify email address |  
  | Almost done, @spiketribe610! To complete your GitHub sign up, we just need to verify your email address: spiketribe320@gmail.com.Verify email addressOnce verified, you can start using all of GitHub's features to explore, build, and share projects.Button not working? Paste the following link into your browser: https://github.com/users/spiketribe610/emails/85359303/confirm_verification/d5fb609e02bebb9fd7b348b97f6cb5e37fa14d1aYou’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.Email preferences · Terms · Privacy · Sign into GitHub | Verify email address | Verify email address |  
Verify email address | Verify email address
Verify email address
Sent with <3 by GitHub.GitHub, Inc. 88 Colin P Kelly Jr StreetSan Francisco, CA 94107 |  
  | ReplyForward
