### ISSUE TITLE
Input for body not visible

### ISSUE THREAD

**Issue by MartinSandberg** [adaptlearning/adapt_authoring#598] opened 2015-03-13 06:27 UTC
Hi,

Tested this in Firefox, Chrome and Internet Explorer. Tried to search for the issue here but did not find it although it is most probably reported already...

All input fields for body field are hidden via css. Seen on the articles, blocks and components as well as on the accordion item.

This example is from the accordion item:

<span data-editor="">
<textarea id="body" name="body" style="visibility: hidden;"></textarea>

If I manipulate the css in the browser I can get the editor and enter the text, that is also saved. But it should not be hidden in the first place.

BR

Martin

**Comment by brian-learningpool** [comment] 2015-03-25 12:33
Hi @MartinSandberg, did you intend to attach a screenshot?

**Comment by Tschakki** [comment] 2015-03-26 12:55
I can confirm this Bug!
Here are screenshots from my instance:
![bildschirmfoto vom 2015-03-26 13 52 03](https://cloud.githubusercontent.com/assets/1993505/6846611/beabdc44-d3bf-11e4-800e-08cb2c599a01.png)
![bildschirmfoto vom 2015-03-26 13 51 44](https://cloud.githubusercontent.com/assets/1993505/6846612/beac32f2-d3bf-11e4-96db-22fd4163a3d7.png)

**Comment by taylortom** [comment] 2017-02-09 12:51
Closing this, as haven't seen this one since the UI refresh.

**Closed by taylortom** 2017-02-09 12:51 UTC
