### ISSUE TITLE
Copy Component allowed even if there is not a free space in a block

### ISSUE THREAD

**Issue by TimFrance** [adaptlearning/adapt_authoring#2423] opened 2019-08-27 10:02 UTC
## Expected Behaviour
The Copy menu entry for a Component should be unavailable (greyed out) if there is no "Add Component" field available.
Alternatively when a Component is copied without an "Add Component" field available the "Add Block" and/or "Add Article" should be visible. Or even a new block in the current or new Article could be created automatically.

## Actual Behaviour
When there is no "Add component" field available, a Copy Component just makes the "Add Block" and "Add Article" buttons disappear. Using "Back to course structure" and double-clicking to return to the page edit gets back to the normal display, so there is an easy work around.

## Steps to Reproduce
1. Use Copy Component when no "Add Component" area is visible

## Versions
  - Authoring Tool Version: 0.9.0
  - Framework Version: 2.4.0
  - Node.js Version: v10.16.3
  - MongoDB Compass Community Version: 1.19.6
  - Operating System: Windows 10
  - Browser: Chome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by tomgreenfield** [comment] 2019-08-28 08:47
Thanks for raising the issue, @TimFrance. This is actually a duplicate of #2320.

**Closed** 2019-08-28 09:01 UTC

**Comment by TimFrance** [comment] 2019-08-28 09:04
Hi Tom

I had searched for it, but we used different terms and it didn't show up.

I have closed the issue.

Thanks

Tim
