### ISSUE TITLE
Assessment wants an assessment name every time

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#1456] opened 2016-11-24 17:18 UTC
When editing other configs in a article I always get asked for the assessment name even though i'm not using assessment on that article.

![image](https://cloud.githubusercontent.com/assets/11558341/20606616/0c1da5d6-b26a-11e6-9b30-dd2083fe4687.png)

**Comment by tomgreenfield** [comment] 2016-11-24 17:36
This is a duplicate of #1293,.

As for the issue, we're just waiting for https://github.com/adaptlearning/adapt-contrib-assessment/pull/72 to be resolved and merged.

**Closed** 2016-11-25 13:32 UTC
