### ISSUE TITLE
Sidebar in editor should be extensible 

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_authoring#2102] opened 2018-10-11 07:32 UTC
## Affected Area
Sidebar in editor and in general.

## Requested Feature
As a developer I should be able to add my own button to the sidebar of the editor. The button should trigger a custom event.

## Use Case
Extend the Autoring Tool with custom features and frontend plugins.

## Current Workaround
Amend the editor module.

**Comment by taylortom** [comment] 2018-10-11 10:06
+1 duplicate of https://github.com/adaptlearning/adapt_authoring/issues/1496

**Closed by taylortom** 2018-10-11 10:06 UTC
Labels: C: Front-end, T: enhancement
