### ISSUE TITLE
Adding available extensions opens the confrirmation dialog, but addition does not happen.

### ISSUE THREAD

**Issue by davewallace** [adaptlearning/adapt_authoring#839] opened 2015-09-18 05:15 UTC
I saw no activity in bash, I feel like I'm missing a bunch of install details, such as those listed in the installation guide for Adapt 2.0

**Comment by taylortom** [comment] 2015-09-22 12:24
Think this is a duplicate of https://github.com/adaptlearning/adapt_authoring/issues/831

**Comment by taylortom** [comment] 2017-02-09 12:51
Closing, as no extra info, and #831 has been fixed.

**Closed by taylortom** 2017-02-09 12:51 UTC
