### ISSUE TITLE
Enhancement : Hidden blocks

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#1295] opened 2016-08-03 15:18 UTC
It would be great if hidden blocks could be slightly differently somehow in course edit mode, such as shaded or outlined in a different colour. This would distinguish those blocks that we have "turned off".

I did also think maybe about an (eye?) icon on each block next to the cog and arrows which is open if visible and lined out if hidden. This could also be used as a toggle button instead of having the true/false dropdown in each block settings? Quicker and more obvious perhaps?

**Comment by taylortom** [comment] 2017-07-03 08:36
Duplicate of #1657

**Closed by taylortom** 2017-07-03 08:36 UTC
