### ISSUE TITLE
Share with users list includes disabled users

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#2329] opened 2019-05-09 15:20 UTC
## Expected Behaviour
Selecting users to share a course with should include only valid users.

## Actual Behaviour
Disabled users are included in the list

## Steps to Reproduce
1. Create an additional user
2. Set that user account to disabled
3. Create a new course and search the 'Share with specific users list'

It will include and allow you to select the disabled user.

## Versions
  - Authoring Tool Version: 0.8.0
  - Framework Version: v2.4.0
  - Node.js Version: n/a
  - MongoDB Version:n/a
  - Operating System:n/a
  - Browser:n/a

**Comment by canstudios-nicolaw** [comment] 2019-05-10 14:31
Closing as duplicate of https://github.com/adaptlearning/adapt_authoring/issues/2268

**Closed by canstudios-nicolaw** 2019-05-10 14:31 UTC
Labels: T: bug
