### ISSUE TITLE
/tmp files not being cleared

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_authoring#2305] opened 2019-04-10 15:33 UTC
## Expected Behaviour
When files are uploaded they should not be kept in /tmp forever.

## Actual Behaviour
We tested uploading an asset and it was uploaded to /tmp/upload_94aca3d35a5e60999cf5a24e38331122 and then copied to /data/adapt_authoring/data/master/assets/76/9e/769e33b779449e2e9acb4bc6cb911f7837568a6d.mp4
However the /tmp file was never cleaned up afterwards.

This appears to be a problem for plugins as well as assets.

If a course requires several videos etc. this can quite quickly start to fill up disk space.

I think the correct solution might need to be discussed. We could possibly put something like the following in the code after /tmp files are successfully uploaded.

```
try {
    fs.unlinkSync(file.path);
} catch(err) {
    logger.log('error', 'Failed to delete /tmp/ file');
 }
```

## Versions
  - Authoring Tool Version: 0.7.1

**Comment by canstudios-nicolaw** [comment] 2019-04-10 15:34
Depending on the size/scope of the solution this could potentially be a candidate for the bug patch 2 milestone. Or we might want to think about adding it to the 'spring clean' release with removing plugins and unused roles.

**Comment by taylortom** [comment] 2019-04-15 14:28
Duplicate of https://github.com/adaptlearning/adapt_authoring/issues/2305

**Closed by taylortom** 2019-04-15 14:28 UTC
Labels: C: Back-end, T: bug

**Comment by canstudios-nicolaw** [comment] 2019-04-16 07:51
This is a duplicate of #2115
