### ISSUE TITLE
being able to show updates for all the plugins available on Github

### ISSUE THREAD

**Issue by aniketdharia** [adaptlearning/adapt_authoring#1423] opened 2016-10-12 09:07 UTC
Currently, the AT only supports updating the core plugins, it should support updating all the plugins even if they are user uploaded.

**Comment by taylortom** [comment] 2016-10-12 09:56
Duplicate of https://github.com/adaptlearning/adapt_authoring/issues/1382

**Closed by taylortom** 2016-10-12 09:56 UTC
