### ISSUE TITLE
Autofill overrides images used in extensions

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#1958] opened 2018-05-04 15:30 UTC
# BUG Template

When you use the autofill feature on the graphic component it overrides any images used by extensions.

## Expected Behaviour

Autofill should only affect images in the `_graphic` object.

## Actual Behaviour

It also fills the component icon and if you then try and turn off the component icon image, it seems to remove the image from the lesson altogether.

## Steps to Reproduce
1. Install the [component icon extension](https://github.com/KingsOnline/adapt-component-icon), or any other extension that uses images
2. Use autofill feature.

## Versions
  - Authoring Tool Version: 0.4.1

**Comment by taylortom** [comment] 2018-05-08 10:41
Duplicate of https://github.com/adaptlearning/adapt_authoring/issues/1488

**Closed** 2018-05-08 10:41 UTC
