### ISSUE TITLE
Hot graphic component: pin placement is not intuitive - uses x/y coordinates and no quick preview (M - v0.2)

### ISSUE THREAD

**Issue by lucyhodge** [adaptlearning/adapt_authoring#700] opened 2015-05-26 16:32 UTC
In progress.

**Comment by taylortom** [comment] 2016-06-22 10:47
Linked to #758

**Comment by taylortom** [comment] 2017-02-09 14:19
Closing, as duplicate of #758

**Closed by taylortom** 2017-02-09 14:19 UTC
