### ISSUE TITLE
Possible to have Check for Update button for user uploaded plugins

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#1434] opened 2016-10-25 16:37 UTC
I now have more user-uploaded plugins than I do AT contributed ones, so I was hoping it might be easy for the AT interface to add onto "(Uploaded by User)" a check for update button - to automatically pull down new releases? 

We'd still need to keep an obvious mark of which ones were in built and which were manually added I guess.

EDIT - Further to this - maybe a "Check ALL for updates" button would be useful on the Plugin page as we start to increase plugin numbers too?

**Comment by taylortom** [comment] 2016-10-25 17:14
Duplicate of https://github.com/adaptlearning/adapt_authoring/issues/1382

**Closed by taylortom** 2016-10-25 17:14 UTC
