### ISSUE TITLE
Editor preloading has emphasised performance issues with large installs

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1765] opened 2017-10-30 12:55 UTC
As we now wait for the editor data to preloaded, we're seeing more obvious slow-down in 'large' installs (it's not entirely clear what categorises large: many courses, courses with a lot of content -- probably both). 

This needs to be investigated.

## Versions
  - Authoring Tool Version: 0.4.0

**Comment by canstudios-louisem** [comment] 2017-10-31 11:36
Isnt this just a duplicate of #1758?

**Closed** 2017-11-01 16:58 UTC
Labels: I: critical, T: bug
