### ISSUE TITLE
Can't delete component items anymore (ex. flipcard)

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt_authoring#1795] opened 2017-11-24 19:12 UTC
**# Can't delete component items anymore (ex. flipcard)**

## Expected Behaviour
Should delete item when the x button is clicked

## Actual Behaviour
Brings up notify that says do you want to delete. When I press Yes nothing happens

## Steps to Reproduce
1. added flipcard component
2. add 1 or more flipcard items in to authoring tool
3. Try deleting one

## Versions
  - Authoring Tool Version: 0.4.0
  - Framework Version: 2.2.3
  - Operating System: Windows 10
  - Browser: Chrome

![flipcard-items-wont-delete](https://user-images.githubusercontent.com/10455453/33221942-7714f52a-d121-11e7-9bbc-f7a2694db596.jpg)

**Comment by tomgreenfield** [comment] 2017-11-27 09:17
This is a duplicate of #1753.

**Closed** 2017-11-27 10:59 UTC
