### ISSUE TITLE
Deleted components do not appear to remove the course assets

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_authoring#1078] opened 2016-03-03 09:44 UTC
This leads to zip files containing more assets than they should, and bigger zip packages.

From the forums:

> We made a big course, with a lot of chapters and videos etc.This course was not really convenient to work with, so we split it up in seperate courses per chapter.This was done by copying the entire course and deleting the chapters that should not be in that particular course.
> 
> the output size of the big Course is 135mb.
> the output size of all the small courses is 135 for each small course.
> We checked the zip files and it turns out that the assets are still in the small courses, even though they are no longer being used.
> 
> It seems there is an error with the builder, that does not update deleted content. is there a solution for this, or should we wait for a new version of the authoring tool.

**Comment by taylortom** [comment] 2016-03-03 11:31
Do we just need to run a clean on the build folder here?

**Comment by brian-learningpool** [comment] 2016-03-03 14:31
The assets folder should always be cleared using `rimraf`anyway.  

This issue seems related to #812.

**Comment by brian-learningpool** [comment] 2016-03-03 14:38
I debugging I was only ever able to see this once and due I suspect to the fact that a DELETE request was firing twice for blocks and components. 

PR #1079 might help with this.

**Comment by sandervanzijl** [comment] 2016-03-08 11:11
It might be usefull to tell you I deleted pages and sections, not individual blocks and components.

**Comment by brian-learningpool** [comment] 2016-04-12 13:25
This issue has been resolved for this release and confirmed resolved for courses created with later versions.

@sandervanzijl, does v0.1.6 resolve your issue?

**Comment by sandervanzijl** [comment] 2016-04-12 14:20
I will try asap, but that might be somewhere next week.

Date: Tue, 12 Apr 2016 06:25:59 -0700

**Comment by sandervanzijl** [comment] 2016-05-02 09:48
OK, did some more testing.

the original copies did not reduce in size when rebuilding them.

however, when i make a copy of the copy and build that, then the size is reduced.
so with this work around, I think the issue can be closed.

**Comment by unclebumpy** [comment] 2017-11-09 22:52
Hi. Is this issue going to be addressed at some point in a release? It's creating a lot of overhead for us given how we create base courses with content and then copy them. We're having to then copy them again after making changes to the copy...

Thanks.

**Comment by JonCollins-ID** [comment] 2018-01-18 11:29
Hi

I have experienced a similar issue with a course including lots of redundant assets. I have tried the workaround suggested above but there is no change in filesize?

Do I understand the workaround correctly @sandervanzijl and you just need to create a copy of a copy of the course, force a rebuild by switching theme back and forth and then download the reduced filesize course?

I've tried and it shows no different filesize?

can you please clarify the process you used @sandervanzijl 

is this issue going to be resolved in a future update?

thanks

**Comment by taylortom** [comment] 2018-01-18 15:31
@unclebumpy, @JonCollins-ID we've fixed a few similar issues in 0.4.0 and 0.4.1 -- will revisit this one for the next release.

**Comment by dancgray** [comment] 2019-02-13 16:46
Much of this seems to have been fixed. The only way I can leave orphaned assets is by deleting a submenu, steps to reproduce as follow:

1. Add any asset to a contentobject, article, block or component on a page that is a child of a submenu
2. delete the sub menu
3. any assets in the page who's parent was the menu are left in courseassets collection and get included in the build/publish/export zip.

The courseasset plugin [hook](https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/content/courseasset/index.js#L66) only checks for contentobjects with articles and does not propagate to child contentobjects.

**Comment by taylortom** [comment] 2024-08-23 17:28
Closing due to inactivity & impending deprecation of the legacy codebase.

**Closed by taylortom** 2024-08-23 17:28 UTC
Labels: T: bug, S: in-progress
