### ISSUE TITLE
Focus filter textbox on add components popout menu

### ISSUE THREAD

**Issue by Deathjam** [adaptlearning/adapt_authoring#1589] opened 2017-03-14 16:56 UTC
Focus filter textbox on add components popout menu so i can start typing what i want.

**Comment by canstudios-nicolaw** [comment] 2019-07-31 13:47
Closing as duplicate of https://github.com/adaptlearning/adapt_authoring/issues/1963

**Closed by canstudios-nicolaw** 2019-07-31 13:47 UTC
Labels: T: enhancement
