### ISSUE TITLE
Menu _lockType can only be set on top-level course

### ISSUE THREAD

**Issue by guzmangr** [adaptlearning/adapt_authoring#1363] opened 2016-09-01 16:31 UTC
The schema needs to be updated to allow this to be set on content objects too.

**Comment by guzmangr** [comment] 2016-09-02 07:42
I do not know how to update the schema. 
I have fear of losing information

**Comment by taylortom** [comment] 2016-09-02 12:20
My updates were instructions for whoever picks this up :)

**Comment by taylortom** [comment] 2017-07-03 08:54
Duplicate of #1625

**Closed by taylortom** 2017-07-03 08:54 UTC
