### ISSUE TITLE
Organize items within components

### ISSUE THREAD

**Issue by mldaq** [adaptlearning/adapt_authoring#1569] opened 2017-03-01 22:15 UTC
Would be helpful if the items within narratives, the reference interface and other components that use the add item feature had the ability to easily reorganize items. Drag and drop would be great but a simple weighted drop down or arrows to move things up and down would be effective.

**Comment by taylortom** [comment] 2017-03-02 09:21
Duplicate of #1430

**Closed by taylortom** 2017-03-02 09:21 UTC
