### ISSUE TITLE
No Article or Block Display Title or Title by default

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#1522] opened 2017-02-15 16:43 UTC
The Display Title and Title attributes for Articles and Blocks should be empty by default. From what I know most users do not use these attributes and delete them straight away.

Currently you aren't allowed an empty Title attribute so would require both allowing this to be allowed so this would require turning off the current name check as well as the further work to make the default article and block not have the attribute. However the DisplayTitle attribute is the one that people notice the most and would be quicker to implement.

**Comment by hmaffin** [comment] 2017-02-15 17:52
I would agree with Simon - I would say a higher percentage of my articles and blocks don't have titles in them than do - so I'd much rather you didn't have to keep deleting them.

**Comment by johnniezen** [comment] 2017-02-16 10:44
I also agree, however when not in, the padding in the Vanilla theme make the page look really weird, so the user needs to be aware that there will be white space, or allow the padding to be turned off.

**Comment by taylortom** [comment] 2017-12-08 14:43
Closing this, as is a more specific duplicate of https://github.com/adaptlearning/adapt_authoring/issues/1505

**Closed by taylortom** 2017-12-08 14:43 UTC
