### ISSUE TITLE
course.model.schema missing when exporting source code

### ISSUE THREAD

**Issue by sharpb** [adaptlearning/adapt_authoring#1639] opened 2017-05-18 11:28 UTC
If I create a course in the AT then export it (Export source code) course.model.schema seems to be missing from src/core/schema/.

If I create a course using CLI (adapt create course) course.model.schema is included.

I found this because I exported a course to translate, but when running `grunt translate:export` I received the error:
`Running "_parseSchemaFiles" task`
`Warning: Cannot read property 'properties' of undefined Use --force to conintue.`

Copying in course.model.schema from CLI created course fixes the issue.

**Comment by dancgray** [comment] 2017-06-08 09:17
Hi @sharpb this looks like a duplicate of #1512. A fix should be in the next release.

**Closed** 2017-07-03 08:43 UTC
Labels: bug
