### ISSUE TITLE
Modifying any component in a authoring tool course doesn't update the "updated date" on Dash

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt_authoring#2091] opened 2018-10-02 13:56 UTC
## Expected Behaviour
Modifying any component in the authoring tool and the Courses **updated date** will be updated.

## Actual Behaviour
If I Modify a component in my course in the authoring tool the Courses **updated date** does not update.
That said it does update if I edit the project settings, page settings, articles settings or modify a block, just not a component for some reason.

## Steps to Reproduce
create a course from scratch. Add component. Wait a day modify component. Course updated date on Dash will not update.

## Versions
Authoring Tool Version: 0.6.0
Framework Version: 2.2.5
Node.js Version: 8.11.2
MongoDB Version:
Operating System: windows 10
Browser: chrome

![course-updated](https://user-images.githubusercontent.com/10455453/46353120-67122000-c629-11e8-8de8-fbcbb6f19c4e.jpg)

**Comment by tomgreenfield** [comment] 2018-10-02 14:00
This is a duplicate of https://github.com/adaptlearning/adapt_authoring/issues/2057.

**Closed** 2018-10-05 11:44 UTC
